export enum ScreenState {
  DEFAULT = "DEFAULT",
  ERROR = "ERROR",
  LOADED = "LOADED",
  LOADED_NO_DATA = "LOADED_NO_DATA",
  LOADING = "LOADING",
}

export enum AlertType {
  ALERT_SUCCESS = "ALERT_SUCCESS",
  ALERT_ERROR = "ALERT_ERROR",
}

export enum HTTP_STATUS_CODE {
  BAD_REQUEST = 400,
  CONFLICT_REQUEST = 409
}
